name: Generate and push docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      # run generate script
      - name: Generate docs 🔧
        run: sh ./docs/generate.sh

      # push to docs repo
      - name: Deploy 🚀
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SCAPI_DEPLOY_KEY }}
        with:
          source-directory: 'docs/api'
          destination-github-username: 'smart-core-os'
          destination-repository-name: 'smart-core-os.github.io'
          target-directory: 'src/api'
          user-email: tom.haskell@vanti.co.uk
          target-branch: main
