name: Generate and push docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          check-latest: true
          cache: true

      - name: Dependencies
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest

      # run generate script
      - name: Generate docs 🔧
        working-directory: ./docs
        run: bash ./generate.sh

      # push to docs repo
      - name: Deploy 🚀
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SCAPI_DEPLOY_KEY }}
        with:
          source-directory: 'docs/api'
          destination-github-username: 'smart-core-os'
          destination-repository-name: 'smart-core-os.github.io'
          target-directory: 'src/api'
          user-email: tom.haskell@vanti.co.uk
          target-branch: main
